### ISSUE TITLE
Magnet

### ISSUE THREAD

**Issue by Hamtar0** [piznel/gladys-xiaomi#9]
Pas de retours d'infos sur le status, juste sur la batterie.
``
_onMessage.msg : { cmd: 'report',
  model: 'magnet',
  sid: '158d000213771e',
  short_id: 10043,
  data: '{"status":"open"}' }
(node:23445) Warning: a promise was created in a handler at /Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/xiaomi.js:100:22 but was not returned from it, see http://goo.gl/rRqMUw
    at Object.ret [as sql] (eval at makeNodePromisifiedEval (/Users/dguillot/Documents/GitHub/gladys/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
_onMessage.msg : { cmd: 'report',
  model: 'vibration',
  sid: '158d0002a4f707',
  short_id: 8981,
  data: '{"status":"vibrate"}' }
_onMessage.msg : { cmd: 'heartbeat',
  model: 'gateway',
  sid: '7811dce1b5f4',
  short_id: '0',
  token: '51dtN2cSYVfpVsCZ',
  data: '{"ip":"192.168.1.124"}' }
_onMessage.msg : { cmd: 'report',
  model: 'magnet',
  sid: '158d000213771e',
  short_id: 10043,
  data: '{"status":"close"}' }
(node:23445) Warning: a promise was created in a handler at /Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/xiaomi.js:100:22 but was not returned from it, see http://goo.gl/rRqMUw
    at Object.ret [as sql] (eval at makeNodePromisifiedEval (/Users/dguillot/Documents/GitHub/gladys/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
_onMessage.msg : { cmd: 'heartbeat',
  model: 'magnet',
  sid: '158d000213771e',
  short_id: 10043,
  data: '{"voltage":3005,"status":"close"}' }
(node:23445) Warning: a promise was created in a handler at /Users/dguillot/Documents/GitHub/gladys/api/hooks/gladys-xiaomi/lib/xiaomi.js:100:22 but was not returned from it, see http://goo.gl/rRqMUw
    at Object.ret [as sql] (eval at makeNodePromisifiedEval (/Users/dguillot/Documents/GitHub/gladys/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
info: Event : create : new Event with code : devicetype-new-value
info: Scenario : Trigger : New event : devicetype-new-value
info: Scenario : Trigger : Found 0 launchers with code devicetype-new-value.
``

**Comment by piznel** [comment]
Ok, ça devrait être corrigé.
